name: Node.js CI

on:
  pull_request:
    branches: [ nx-app ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run translate service
      run: |
           npm run libretranslate
           docker ps
    - name: Build
      run: |
           export SERVER_URL=127.0.0.1
           npm run build
    - name: Stop translate service
      run: npm run libretranslate-stop
    
