name: Deploy

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - name: Checkout cached-translation-middleware
      uses: actions/checkout@v6
      with:
        persist-credentials: false
        repository: caiocampos/cached-translation-middleware

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Build batch
      run: bash batch-build.sh

    - name: Run libretranslate
      run: bash libretranslate.sh

    - name: Run batch
      run: ./batch

    - name: Stop libretranslate
      run: bash libretranslate-stop.sh
