name: Limpar Branches

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Stale Branches
        uses: crs-k/stale-branches@v9.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 90
          days-before-delete: 105
          branches-filter-regex: '^((dependabot))'
